### ISSUE TITLE
dpc_common.hpp path update

### ISSUE THREAD

**Issue by zjin-lcf** [oneapi-src/oneAPI-samples#119]
# Summary
Provide a short summary of the issue. Sections below provide guidance on what
factors are considered important to reproduce an issue.

Could you please update the CMake files to include the path to dpc_common.hpp ?

Does `%ONEAPI_ROOT%\dev-utilities\latest\include` exist ?

Thanks

**Comment by xmnboy** [comment]
Hi @zjin-lcf -- thanks for the feedback.

If you are searching for the `%ONEAPI_ROOT%\dev-utilities\latest\include` folder on Windows you must quotes the directory name, for example:
```
> dir "%ONEAPI_ROOT%\dev-utilities\latest\include"
```
This is due to the spaces in the "\Program Files (x86)\" folder name that is part of the `%ONEAPI_ROOT%` environment variable (on a typical install).

In order to use any of the oneAPI tools at the command-line, for example if you are using cmake (or make), requires that you first run the setvars script (`setvars.bat` on Windows and `setvars.sh` on Linux and macOS) to initialize your local environment variables. The `dev-utilities` component contributes to the env var setup, when you run setvars.

After running `setvars.bat` on your system you will see that the CPATH and INCLUDE environment variables will include a reference to `%ONEAPI_ROOT%\dev-utilities\latest\include`. For example, see the list below (I've limited the output to env vars that include the dev-utilities folder and have expanded them with `tr` to make the paths easier to read):

```
C:\Users\paul>set | find /i "dev-util" | wsl -- tr \;= \\n
CPATH
C:\Program Files (x86)\Intel\oneAPI\tbb\latest\env\..\include
C:\Program Files (x86)\Intel\oneAPI\ippcp\latest\include
C:\Program Files (x86)\Intel\oneAPI\ipp\latest\include
C:\Program Files (x86)\Intel\oneAPI\dpcpp-ct\latest\env\..\include
C:\Program Files (x86)\Intel\oneAPI\dev-utilities\latest\include

INCLUDE
C:\Program Files (x86)\Intel\oneAPI\vpl\latest\include
C:\Program Files (x86)\Intel\oneAPI\tbb\latest\env\..\include
C:\Program Files (x86)\Intel\oneAPI\ippcp\latest\include
C:\Program Files (x86)\Intel\oneAPI\ipp\latest\include
C:\Program Files (x86)\Intel\oneAPI\dpcpp-ct\latest\env\..\include
C:\Program Files (x86)\Intel\oneAPI\dnnl\latest\env\..\cpu_dpcpp_gpu_dpcpp\include
C:\Program Files (x86)\Intel\oneAPI\dev-utilities\latest\include

Path
C:\Program Files (x86)\Intel\oneAPI\vtune\latest\bin64
C:\Program Files (x86)\Intel\oneAPI\vpl\latest\bin
C:\Program Files (x86)\Intel\oneAPI\tbb\latest\env\..\redist\intel64\vc_mt
C:\Program Files (x86)\Intel\oneAPI\system_debugger\2021.1-beta08\windbg-ext
C:\Program Files (x86)\Intel\oneAPI\ippcp\latest\redist\intel64
C:\Program Files (x86)\Intel\oneAPI\ipp\latest\redist\intel64
C:\Program Files (x86)\Intel\oneAPI\dpcpp-ct\latest\env\..\bin
C:\Program Files (x86)\Intel\oneAPI\dnnl\latest\env\..\cpu_dpcpp_gpu_dpcpp\bin
C:\Program Files (x86)\Intel\oneAPI\dev-utilities\latest\bin
C:\WINDOWS\system32
C:\WINDOWS
C:\WINDOWS\System32\Wbem
C:\WINDOWS\System32\WindowsPowerShell\v1.0\
C:\WINDOWS\System32\OpenSSH\
C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\
C:\Python36
C:\Program Files (x86)\sw_dev_tools\tools\DAL_1.2012.1214.110\
C:\Program Files\CMake\bin
C:\IntelSWTools\sw_dev_tools\tools\DAL_1.2012.1214.110\
C:\Users\paul\AppData\Local\Microsoft\WindowsApps

C:\Users\paul\AppData\Local\Programs\Microsoft VS Code\bin
C:\Program Files (x86)\Intel\oneAPI\system_debugger\2021.1-beta08\tools\python3
C:\Program Files (x86)\Intel\oneAPI\system_debugger\2021.1-beta08\tools\python3\Scripts

C:\Users\paul>
```
Having run the setvars script will insure that the compilers will find the common include folder.

I hope this helps,

Paul

> p.s. Using cmake with most of the oneAPI samples, on Windows, is currently not supported with the beta releases of the oneAPI tools. The cmake build scripts included with the samples currently only work on Linux. The cmake discovery process on Windows is not yet working with the dpcpp compiler. We hope to have a solution for this problem, but until then, you must use the Visual Studio GUI or use MSBuild at the command line to build the samples. See the sample's README for help with command-line builds on Windows.
